export interface raipur {
        "id": "string",
        "h1": "string",
        "h6": "string",
        "p1": "string",
        "h01": "string",
        "h06": "string",
        "img06": "string",
        "p2": "string",
        "h006": "string",
        "img006": "string",
        "p3": "string" ,
        "h0006": "string",
        "img0006":"string",
        "p4": "string",
        "h00006": "string ",
        "img00006": "string",
        "p5": "string",
        "go":"string",
        "go01":"string",
        "goh6":"string",
        "go02":"string",
        "hoh06":"string",
        "go03":"string",
        "goh006":"string",
        "go04":"string"
}
export interface gangrel {
        "id": "string",
        "h1": "string",
        "h6": "string",
        "p1": "string",
        "h01": "string",
        "h06": "string",
        "img06": "string",
        "p2": "string",
        "h006": "string",
        "img006": "string",
        "p3": "string" ,
        "h0006": "string",
        "img0006":"string",
        "p4": "string",
        "h00006": "string ",
        "img00006": "string",
        "p5": "string",
        "go":"string",
        "go01":"string",
        "goh6":"string",
        "go02":"string",
        "hoh06":"string",
        "go03":"string",
        "goh006":"string",
        "go04":"string"
}
export interface sirpur {
        "id": "string",
        "h1": "string",
        "h6": "string",
        "p1": "string",
        "h01": "string",
        "h06": "string",
        "img06": "string",
        "p2": "string",
        "h006": "string",
        "img006": "string",
        "p3": "string" ,
        "h0006": "string",
        "img0006":"string",
        "p4": "string",
        "h00006": "string ",
        "img00006": "string",
        "p5": "string",
        "go":"string",
        "go01":"string",
        "goh6":"string",
        "go02":"string",
        "hoh06":"string",
        "go03":"string",
        "goh006":"string",
        "go04":"string"
}
export interface rajim {
        "id": "string",
        "h1": "string",
        "h6": "string",
        "p1": "string",
        "h01": "string",
        "h06": "string",
        "img06": "string",
        "p2": "string",
        "h006": "string",
        "img006": "string",
        "p3": "string" ,
        "h0006": "string",
        "img0006":"string",
        "p4": "string",
        "h00006": "string ",
        "img00006": "string",
        "p5": "string",
        "go":"string",
        "go01":"string",
        "goh6":"string",
        "go02":"string",
        "hoh06":"string",
        "go03":"string",
        "goh006":"string",
        "go04":"string"
}
export interface barnawapara {
        "id": "string",
        "h1": "string",
        "h6": "string",
        "p1": "string",
        "h01": "string",
        "h06": "string",
        "img06": "string",
        "p2": "string",
        "h006": "string",
        "img006": "string",
        "p3": "string" ,
        "h0006": "string",
        "img0006":"string",
        "p4": "string",
        "h00006": "string ",
        "img00006": "string",
        "p5": "string",
        "go":"string",
        "go01":"string",
        "goh6":"string",
        "go02":"string",
        "hoh06":"string",
        "go03":"string",
        "goh006":"string",
        "go04":"string"
}
export interface champaranya {
        "id": "string",
        "h1": "string",
        "h6": "string",
        "p1": "string",
        "h01": "string",
        "h06": "string",
        "img06": "string",
        "p2": "string",
        "h006": "string",
        "img006": "string",
        "p3": "string" ,
        "h0006": "string",
        "img0006":"string",
        "p4": "string",
        "h00006": "string ",
        "img00006": "string",
        "p5": "string",
        "go":"string",
        "go01":"string",
        "goh6":"string",
        "go02":"string",
        "hoh06":"string",
        "go03":"string",
        "goh006":"string",
        "go04":"string"
}
export interface chitrakote {
        "id": "string",
        "h1": "string",
        "h6": "string",
        "p1": "string",
        "h01": "string",
        "h06": "string",
        "img06": "string",
        "p2": "string",
        "h006": "string",
        "img006": "string",
        "p3": "string" ,
        "h0006": "string",
        "img0006":"string",
        "p4": "string",
        "h00006": "string ",
        "img00006": "string",
        "p5": "string",
        "go":"string",
        "go01":"string",
        "goh6":"string",
        "go02":"string",
        "hoh06":"string",
        "go03":"string",
        "goh006":"string",
        "go04":"string"
}
export interface tirathgarh {
        "id": "string",
        "h1": "string",
        "h6": "string",
        "p1": "string",
        "h01": "string",
        "h06": "string",
        "img06": "string",
        "p2": "string",
        "h006": "string",
        "img006": "string",
        "p3": "string" ,
        "h0006": "string",
        "img0006":"string",
        "p4": "string",
        "h00006": "string ",
        "img00006": "string",
        "p5": "string",
        "go":"string",
        "go01":"string",
        "goh6":"string",
        "go02":"string",
        "hoh06":"string",
        "go03":"string",
        "goh006":"string",
        "go04":"string"
}
export interface bhoramdeo {
        "id": "string",
        "h1": "string",
        "h6": "string",
        "p1": "string",
        "h01": "string",
        "h06": "string",
        "img06": "string",
        "p2": "string",
        "h006": "string",
        "img006": "string",
        "p3": "string" ,
        "h0006": "string",
        "img0006":"string",
        "p4": "string",
        "h00006": "string ",
        "img00006": "string",
        "p5": "string",
        "go":"string",
        "go01":"string",
        "goh6":"string",
        "go02":"string",
        "hoh06":"string",
        "go03":"string",
        "goh006":"string",
        "go04":"string"
}
export interface dongargarh {
        "id": "string",
        "h1": "string",
        "h6": "string",
        "p1": "string",
        "h01": "string",
        "h06": "string",
        "img06": "string",
        "p2": "string",
        "h006": "string",
        "img006": "string",
        "p3": "string" ,
        "h0006": "string",
        "img0006":"string",
        "p4": "string",
        "h00006": "string ",
        "img00006": "string",
        "p5": "string",
        "go":"string",
        "go01":"string",
        "goh6":"string",
        "go02":"string",
        "hoh06":"string",
        "go03":"string",
        "goh006":"string",
        "go04":"string"
}
export interface ratanpur {
        "id": "string",
        "h1": "string",
        "h6": "string",
        "p1": "string",
        "h01": "string",
        "h06": "string",
        "img06": "string",
        "p2": "string",
        "h006": "string",
        "img006": "string",
        "p3": "string" ,
        "h0006": "string",
        "img0006":"string",
        "p4": "string",
        "h00006": "string ",
        "img00006": "string",
        "p5": "string",
        "go":"string",
        "go01":"string",
        "goh6":"string",
        "go02":"string",
        "hoh06":"string",
        "go03":"string",
        "goh006":"string",
        "go04":"string"
}
export interface tala {
        "id": "string",
        "h1": "string",
        "h6": "string",
        "p1": "string",
        "h01": "string",
        "h06": "string",
        "img06": "string",
        "p2": "string",
        "h006": "string",
        "img006": "string",
        "p3": "string" ,
        "h0006": "string",
        "img0006":"string",
        "p4": "string",
        "h00006": "string ",
        "img00006": "string",
        "p5": "string",
        "go":"string",
        "go01":"string",
        "goh6":"string",
        "go02":"string",
        "hoh06":"string",
        "go03":"string",
        "goh006":"string",
        "go04":"string"
}
export interface achankamar {
        "id": "string",
        "h1": "string",
        "h6": "string",
        "p1": "string",
        "h01": "string",
        "h06": "string",
        "img06": "string",
        "p2": "string",
        "h006": "string",
        "img006": "string",
        "p3": "string" ,
        "h0006": "string",
        "img0006":"string",
        "p4": "string",
        "h00006": "string ",
        "img00006": "string",
        "p5": "string",
        "go":"string",
        "go01":"string",
        "goh6":"string",
        "go02":"string",
        "hoh06":"string",
        "go03":"string",
        "goh006":"string",
        "go04":"string"
}
export interface girodhpuri {
        "id": "string",
        "h1": "string",
        "h6": "string",
        "p1": "string",
        "h01": "string",
        "h06": "string",
        "img06": "string",
        "p2": "string",
        "h006": "string",
        "img006": "string",
        "p3": "string" ,
        "h0006": "string",
        "img0006":"string",
        "p4": "string",
        "h00006": "string ",
        "img00006": "string",
        "p5": "string",
        "go":"string",
        "go01":"string",
        "goh6":"string",
        "go02":"string",
        "hoh06":"string",
        "go03":"string",
        "goh006":"string",
        "go04":"string"
}
export interface mainpat {
        "id": "string",
        "h1": "string",
        "h6": "string",
        "p1": "string",
        "h01": "string",
        "h06": "string",
        "img06": "string",
        "p2": "string",
        "h006": "string",
        "img006": "string",
        "p3": "string" ,
        "h0006": "string",
        "img0006":"string",
        "p4": "string",
        "h00006": "string ",
        "img00006": "string",
        "p5": "string",
        "go":"string",
        "go01":"string",
        "goh6":"string",
        "go02":"string",
        "hoh06":"string",
        "go03":"string",
        "goh006":"string",
        "go04":"string"
}
export interface baster {
        "id": "string",
        "h1": "string",
        "h6": "string",
        "p1": "string",
        "h01": "string",
        "h06": "string",
        "img06": "string",
        "p2": "string",
        "h006": "string",
        "img006": "string",
        "p3": "string" ,
        "h0006": "string",
        "img0006":"string",
        "p4": "string",
        "h00006": "string ",
        "img00006": "string",
        "p5": "string",
        "go":"string",
        "go01":"string",
        "goh6":"string",
        "go02":"string",
        "hoh06":"string",
        "go03":"string",
        "goh006":"string",
        "go04":"string"
}
export interface madku {
        "id": "string",
        "h1": "string",
        "h6": "string",
        "p1": "string",
        "h01": "string",
        "h06": "string",
        "img06": "string",
        "p2": "string",
        "h006": "string",
        "img006": "string",
        "p3": "string" ,
        "h0006": "string",
        "img0006":"string",
        "p4": "string",
        "h00006": "string ",
        "img00006": "string",
        "p5": "string",
        "go":"string",
        "go01":"string",
        "goh6":"string",
        "go02":"string",
        "hoh06":"string",
        "go03":"string",
        "goh006":"string",
        "go04":"string"
}
export interface kanger {
        "id": "string",
        "h1": "string",
        "h6": "string",
        "p1": "string",
        "h01": "string",
        "h06": "string",
        "img06": "string",
        "p2": "string",
        "h006": "string",
        "img006": "string",
        "p3": "string" ,
        "h0006": "string",
        "img0006":"string",
        "p4": "string",
        "h00006": "string ",
        "img00006": "string",
        "p5": "string",
        "go":"string",
        "go01":"string",
        "goh6":"string",
        "go02":"string",
        "hoh06":"string",
        "go03":"string",
        "goh006":"string",
        "go04":"string"
}